image:
  name: docker/compose:1.25.0-rc2-alpine # Pick latest one - no tag 'latest' available
  entrypoint: ["/bin/sh", "-c"]

variables:
  # When using dind service we need to instruct docker to talk with the
  # daemon started inside of the service. The daemon is available with
  # a network connection instead of the default /var/run/docker.sock socket.
  DOCKER_HOST: tcp://docker:2375/
  # When using dind, it's wise to use the overlayfs driver for
  # improved performance.
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

before_script:
  - apk add --no-cache make

unit tests:
  stage: test
  script:
  - make unittests

integration tests:
  stage: test
  script:
  - make integration-setup
  - make integration
  - make integration-logs
  - make integration-teardown
