before_script:
 - apk add --no-cache make

unit tests:
  stage: test
  image: golang:1.8-alpine
  script:
   - mkdir -p $GOPATH/src/github.com/dlorch
   - ln -s $CI_PROJECT_DIR $GOPATH/src/github.com/dlorch/base-nfs
   - cd $GOPATH/src/github.com/dlorch/base-nfs
   - make unittests

integration tests:
  stage: test
  image:
    name: docker/compose:1.25.0-rc2-alpine # Pick latest one - no tag 'latest' available
    entrypoint: ["/bin/sh", "-c"]
  services:
   - docker:dind
  variables:
    # When using dind service we need to instruct docker to talk with the
    # daemon started inside of the service. The daemon is available with
    # a network connection instead of the default /var/run/docker.sock socket.
    DOCKER_HOST: tcp://docker:2375/
    # When using dind, it's wise to use the overlayfs driver for
    # improved performance.
    DOCKER_DRIVER: overlay2
  script:
   - make integration-setup
   - make integration
   - make integration-logs
   - make integration-teardown
